language: node_js
node_js:
  - 12
before_script:
  - export NODE_OPTIONS="--max_old_space_size=8192"
jobs:
  include:
    - stage: refs
      script: yarn crawlStaticRefs public/index.ts
    -
      script: yarn crawlStaticRefs server/index.ts
    -
      script: yarn crawlContractRefs public/plugin.ts
    -
      script: yarn crawlContractRefs server/plugin.ts
    - stage: api
      script: yarn crawlContractApi
    -
      script: yarn crawlStaticApi
cache: yarn
