# This is a basic workflow to help you get started with Actions

name: Index issues

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.1
    # Runs a single command using the runners shell
    - name: Trigger TravisCI
      run: ./trigger_travis.sh
